Test: perform query testing
Signed-off-by: Matthew Watkins <mwatkins@linuxfoundation.org>

diff --git a/action.yaml b/action.yaml
--- a/action.yaml
+++ b/action.yaml
@@ -64,8 +64,14 @@ runs:
 
         sorted=$(echo "$releases" |\
         jq "sort_by(.tagName)$REVERSE.[0] | select(.isDraft==true) $flags")
+        echo "$sorted"
+
+        if [ -z "$sorted" ]; then
+          echo "Error: no draft releases matched provided inputs ❌"
+          # exit 1 # Re-instate when finished debugging
+          exit 0
+        fi
 
         # Use of GitHub CLI requires a valid token
         echo "# Promote Draft Release ⏫" >> "$GITHUB_STEP_SUMMARY"
-        echo "$sorted"
         echo "$sorted" >> "$GITHUB_STEP_SUMMARY"
