Fix: Name selection not working
Signed-off-by: Matthew Watkins <mwatkins@linuxfoundation.org>

diff --git a/action.yaml b/action.yaml
--- a/action.yaml
+++ b/action.yaml
@@ -113,7 +113,7 @@ runs:
         fi
         # Selection/filter options can be stacked
         if [ -n "$name" ]; then
-          selected_release=$(echo "$selected_release" | jq "[.[] | select(.name==\"$tag\")]")
+          selected_release=$(echo "$selected_release" | jq "[.[] | select(.name==\"$name\")]")
         fi
 
         # Return first result from whatever element(s) remain
@@ -121,7 +121,8 @@ runs:
         echo "$selected_release"
 
         if [ -z "$selected_release" ]; then
-          echo "Error: GitHub CLI command returned no results ❌"; exit 1
+          echo "Error: GitHub CLI command returned no results ❌"
+          exit 1
         elif [ "$ACTIONS_STEP_DEBUG" == 'true' ]; then
           echo "Sorted GitHub API query data 🐞"
           echo "$selected_release"
@@ -129,22 +130,21 @@ runs:
 
         # Promote release using tagName
         tagName=$(echo "$selected_release" | jq '.tagName' | sed 's:"::g')
-
         # Set release as latest if requested by input
         if [ "${{ inputs.LATEST }}" = 'true' ]; then
           release_flags="--latest"
         else
           unset release_flags
         fi
-
-        release_url=$(gh release edit "$tagName" --draft=false $release_flags)
-        if [ $# -eq 0 ]; then
+        release_url=$(gh release edit "$tagName" --draft=false $release_flags || true)
+        if [ -n "$release_url" ]; then
           echo "Release promoted: $release_url ✅"
         else
-          echo "Error: GitHub CLI failed to promote release ❌"; exit 1
+          echo "Error: GitHub CLI failed to promote release ❌"
+          exit 1
         fi
 
-        # Use of GitHub CLI requires a valid token
+        # Summary output
         echo "# Promoted Draft Release ⏫" >> "$GITHUB_STEP_SUMMARY"
         echo "$release_url" >> "$GITHUB_STEP_SUMMARY"
         if [ "${{ inputs.RELEASE_SUMMARY }}" = 'true' ]; then
